# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Cquantile <- function(x, q) {
    .Call(`_modsymmtest_Cquantile`, x, q)
}

#' @export
get_V <- function(x_, y_ = NULL) {
    .Call(`_modsymmtest_get_V`, x_, y_)
}

